## Composer configuration.
##
composer:

  ## List of composer packages to require when the image is being built.
  ##
  require:
    - behat/mink-selenium2-driver:^1.4
    - drupal/devel
    - drush/drush
    - phpunit/phpunit:^8.4.1
    - symfony/phpunit-bridge:^4.4

## Module configuration.
##
modules:

  ## Which git protocol to use when cloning modules.
  ##
  git_protocol: ssh

  ## List of modules to clone.
  ##
  clone: []
    # - require_on_publish

  ## List of modules to enable when running the install script.
  ##
  enable:
    - devel

## Theme configuration.
##
themes:

  ## List of themes to clone from https://git.drupalcode.org.
  ##
  clone: []
    # - olivero

  ## List of themes to enable when running the install script.
  ##
  enable:
    - claro
