version: '3.7'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    restart: always

  php:
    build:
      context: ../
      args:
        drupal_version: 9-apache
    working_dir: /opt/drupal
    environment:
      COMPOSER_MEMORY_LIMIT: -1
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  chrome:
    image: selenium/standalone-chrome:4.0.0-beta-3-prerelease-20210329
    shm_size: 2g
    ports:
      - 5901:5900
