version: '3.7'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    restart: always

  php:
    build:
      context: ../
      args:
        drupal_version: 9-apache
    environment:
      COMPOSER_MEMORY_LIMIT: -1
    ports:
      - 8080:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_sites:/var/www/html/sites
      - drupal_themes:/var/www/html/themes
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  chrome:
    image: drupalci/webdriver-chromedriver:production
    ulimits:
      core:
        soft: -1
        hard: -1
    cap_add:
      - SYS_ADMIN
    volumes:
      - /dev/shm:/dev/shm
    entrypoint:
      - chromedriver
      - "--no-sandbox"
      - "--log-path=/tmp/chromedriver.log"
      - "--verbose"
      - "--whitelisted-ips="

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_sites:
  drupal_themes:
